apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pgbouncer-operator
  template:
    metadata:
      labels:
        name: pgbouncer-operator
    spec:
      serviceAccountName: pgbouncer-operator
      containers:
        - name: pgbouncer-operator
          image: quay.io/pgbouncer-operator/pgbouncer-operator:v0.0.1
          command:
          - pgbouncer-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pgbouncer-operator"
